apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: emart
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: dev-aws-ecr-us-east-1  #change
      containers:
        - name: api
          image: 532739883212.dkr.ecr.us-west-2.amazonaws.com/api:v1  #change
          imagePullPolicy: Always
          ports:
            - name: api-port
              containerPort: 5000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"


