apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: emart  
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi  
  template:
    metadata:
      labels:
        app: webapi
    spec:
      imagePullSecrets:
      - name: dev-aws-ecr-us-east-1  # change   
      containers:
        - name: webapi
          image: 532739883212.dkr.ecr.us-west-2.amazonaws.com/webapi:1 #change
          imagePullPolicy: Always
          ports:
            - name: webapi-port
              containerPort: 9000
          env:
          - name: MONGOURI
            value: 'mongodb://emongo:27017/epoc'
          - name: SECRETORKEY
            value: 'k1234e6s78h9av'
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
   
