# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: emartdb
  namespace: emart
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
