apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: emart
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.25
        ports:
        - name: mysql-port
          containerPort: 3306
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: mysqldbname
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: mysql-pass
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
