apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: wp-prod-issuer
  namespace: wordpress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: o.olumoyin@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx